### ISSUE TITLE
Latest version feedback & suggestions

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#12]
**User Interface (0.5)**

**Search**
New search has a few problems which keeps it from being as easy to use compared to the old UI.
1. Hard to do a search without using autocomplete since it blocks the "search" button.
2. Auto complete is only showing three results at a time
3. Hidden search box makes it hard to see current filters
I would like to see a big long search bar at the top left of the GUI maybe add a keybind (ctrl+f or tab) for quick access.

**UI**
The new UI does lots of things right, hiding the side-bar for instance gives a lot of room for the galleries and desk-top space. Back/forward buttons now work with mouse buttons and some other small improvements as well.

**Scrollbar** (Minor)
While having a themed scrollbar is nice and it's rather small there are a few problems, first of all you can't select it or hover over the bar. It is only used to display where you are on the page, this is slightly confusing when you try to drag it up and you end up scrolling down.

**Navigation** (Minor)
The go-to page button could be replaced with a page number that you can also use as a go-to function by typing a page number or a drop-down like before.

**Misc**
It would be nice to be shown the current sorting method as well.

Maybe a option to paste EX links into a gallery so it's quicker to fix them manually.

I also preferred the theme of the old GUI as it looked similar to the ex website, hopefully you can add support for themes or something in the future.

**Comment by seanegoodwin** [comment]
Definitely appreciate UI feedback as it's the hardest thing to do, and the least objective.

I'm definitely interested in seeing the comparison. The new version has smaller next, but not that smaller. At least, it shouldn't be. I've attached an image of what I looks like on my computer. It's possible the way the dpi is being calculated is bugged.

The current implementation of the search is pretty shit, yeah. I planned on having it just be a bar in the top right, but I ran into problems. I'll probably try and spend some time and see if I can resolve it.
You can press enter to search though. I shouldn't be hiding the button, but it is possible not to use it.
I figured that 3 options was a decent amount considering most tags aren't really similar (in my experience two letters pretty much narrows it down immediately). But this is easy to change. Maybe I'll make it a user setting.

The scroll bar is purely cosmetic. Because the framework I'm using was initially designed for mobile stuff only there are some growing pains adapting it to the desktop. I wanted to have the scrollbar work properly, but I sort of wanted to get this out before it spent another two weeks sitting on my computer.

![untitled](https://cloud.githubusercontent.com/assets/1712653/8322404/8a8ba3c0-1a02-11e5-8c75-28bc421300d5.png)

**Comment by Black-Light** [comment]
Thats odd your UI looks much bigger then mine, I put my UI next to yours and its a LOT smaller i'll post another screen in a minute.

I tried changing my resolution from 2560x1440 to 1920x1080 but that didn't help.

**Comment by kunikomithra** [comment]
would be cool if you could right click the album covers instead of those 3 dots at the bottom to the right

**Comment by Black-Light** [comment]
Yeah I would like the right-click functionality back as well but I thought it was pretty minor so i didn't include it in the OP.

**Comment by seanegoodwin** [comment]
I added a new version - it should address most of the feedback.

**Comment by Black-Light** [comment]
Amazing update! I am really happy about the new search bar, average ratings and all the fixes.

There are still some issues mostly the searches being slow compared to before when they were instant also a low character count for titles making them hard to read and no proper scroll-bar being some of the main problems I am having. Also it looks like there is a 2 second delay on the tool-tip which should be shortened to 1second or even made instant like before.

There also seems to be a minor problem with the tool-tip if a gallery uses a wide thumbnail you have to mouse over the image to get it to appear the white-space below doesn't do anything. And the wide thumbnails should be vertically centered like before.

Finally the info page for galleries could be improved, when you have a gallery with a lot of tags it doesn't show them all despite there being a lot of screen-space available.

With the titles i was thinking you could make them use 2 lines by removing the settings button (use right-click instead) and move the ratings so it overlays the album art. Then there would be quite a bit more room, just an idea.

**Comment by Black-Light** [comment]
**0.5.2**
The speed improvements are great searching, sorting changing page and even start-up are much faster. It's still not almost instant like the old frameworks speed but overall much better than before.

I would like to see the smooth-scrolling while using the scroll-wheel removed as it can make scrolling very slow.

**Comment by seanegoodwin** [comment]
This will probably be the fastest it will get, unless I discover something new or there are improvements upstream. I'm already using a fair amount of "hacks" to get it where it is now (some of which people might notice).

I increased the scroll cache size in the newest version - is scrolling still slow?

**Comment by Black-Light** [comment]
The problem with scrolling is more to do with the scroll wheel, open pandaviewer and scroll REALLY fast sometimes it hardly moves. But if you scroll slow then fast it goes super quick hard to explain but you will see what I mean,

**Comment by Meowmel** [comment]
>Also I'm not sure if it's just this version but the start-up time on 0.5.3 takes a long time (around 40s) after first booting windows, after that the start-up speed is fine again.
I just laughed. My good old start up times of 7-10 _minutes_ are back with the new versions. Seeeeane why are you doing this to me?
https://www.dropbox.com/s/f55lsza7tndfinw/2015-07-11-18.38.34.log?dl=0

**Comment by Meowmel** [comment]
To add something: I find it a bit troublesome, that PV stops downloading metadata as soon as it finds some broken gallery. I just went afk for 6h and PV downloaded exactly 2 gallery metadata... (ERROR UnknownArchiveError raised with message Sorry, the archive file you tried to access is unable to be opened..)
It would be nice, if there was some kind of option to maybe just move said galleries to a "broken gallerys"/"what ever the user chooses" folder instead of an immediate stop. Going through the log via hand and searching for the broken files just takes to damn much time - just spend 45+min and theres no end to it. :\ 

Second, maybe add some kind of "search for duplicates" option?

**Comment by seanegoodwin** [comment]
Sorry - been really busy. 
For the loading time problems - can you try this build? https://github.com/seanegoodwin/PandaViewer/releases/tag/v0.5.3.1

If it is still bad, send me the archive.stats and folder.stats files. 

We shouldn't really fail hard for gathering metadata if a gallery is busted - I'll make some improvements in that area. As for the other suggestions - duplicate finding is planned "soon". I'll look into having the ability to move broken archives to some folder or something.

**Comment by Meowmel** [comment]
With the 0.5.3.1 the startup takes ~4:30min. That's at least a bit better than before.  But where are the 2 .stats files? Couldn't find the in the PV folder or .lsv folder. 
And good to hear you're working on the other suggestions.

**Comment by seanegoodwin** [comment]
They should've been in the PV folder - they were working for me. 
Anyway, I suspect I fixed the problem. Try this build: https://github.com/seanegoodwin/PandaViewer/releases/tag/v0.5.3.2

**Comment by Meowmel** [comment]
First time: 29 seconds
Second time: 3 seconds.
Third time: 2 seconds.  Aww yiss.
It stays at 2-3 seconds after some more tries. Better than ever before, thanks.

**Comment by seanegoodwin** [comment]
I don't think there's anything left here. Any other issues or suggestions should get their own issue.
