### ISSUE TITLE
Requested features and a question

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#2]
Currently there is no segregation of search results between the folder/file name and the tag results.
As example, searching for anal will give results with anal in the name and in the tags. My proposed solutions are to either make a separate search bar for tags only or do something like tag:anal. With the former, optimally it would be possible to use both at once. The first search bar could display results for anything in the title,  such as convention, franchise, artist, circle, translator, and so on. The second search bar would be for tags only, which given how the metadata works, does include some of the above already. The other way would be to do something like tag:anal tag:double_penetration -tag:loli 

EDIT: Now that I read back through this after having typed it a bit ago and thought it over, I'm not sure if this is actually an issue. After all, if it has the tag name in the folder name, it will probably be tagged as such. I probably should use it more and not type things out without thinking them through better. That, or actually I had a point before then I forgot. Probably the former. Certainly a poorly chosen example in any case. 

Although it isn't really a concern of mine at this time, it may be of others, for a way to differentiate manga and doujinshi results. As for how this could be accomplished, I'd say either through metadata or since you allow for easy adding of various folders, could be that everything is labeled according to the folder it comes from. Everything in the manga folder is a h-manga, everything in the doujinshi folder is a doujinshi folder is a doujinshi and so on. 

If possible, I would appreciate having a grid view as well for a quick overview of a lot of search results that shows the name in one column and tags in the other. 

Manga-Organizer has a chart and list by tag percentage, which is neat, but I wonder if it'd be much use. Hmm. 

From your  "TODO" 
Allow user to pick from choices if no definite gallery is found.
Allow custom tagging/editing of galleries. < -- If this is added, would they be overwritten by fetching metadata? If so, I wonder how useful it would be. More personalization is certainly welcomed though. 

I noticed that you wrote "I'd advise against using the auto search feature right now." on Mar 2.
Is that still the case?

I really don't understand the sorting by title. At all. I'm unable to discern any pattern at all. 

I'm tentatively going to say this is the best program I've seen overall for this, of the three other similar programs that I know about on github. I found it when you, or someone else, linked here in response to my "insanity" of my manual tagging experiment with XYplorer on /a/ recently.

**Comment by seanegoodwin** [comment]
Replies are grouped by the paragraph/topic they respond to.

This was something I thought about doing when I first started working on this, but I don't think it is worth it, for pretty much the same reasons. If I were to do something like that, it'd probably be the inverse, specifying title (e.g. title:baby's first doijinshi) instead of the tags as I think tag searching is more useful. Assuming you have metadata on galleries of course.

This is an interesting idea, and I might consider this in the future. But it wouldn't be for a while. In the meanwhile, people who want something like this could add an extra tag to manga galleries. Obviously not automated, but better than nothing.

I'm assuming you mean a list view, where each gallery is a displayed as a row (what I do now is already a grid). This is planned, but I have no time frame on completion. The entire UI is being rewritten right now, so it would be some time after that. 

I'm not sure what you mean by list by tag percentage. Something like "10% of galleries have tag 'X'"?

Custom tagging is already supported, all of the TODO needs to be rewritten. Right click on a gallery and hit edit. Anything you add will not overwrite data you might have from EX. Of course, this means that if the data from EX is bad, you can't manually remove tags. 

You should* be able to use the auto search (this really should be renamed) feature and not get banned. I rewrote it to be more conservative and I let it run on a loop for hours with no problem. The one other user that uses this has also used it successfully. That said, there is some risk. Definitely don't be browsing EX on a browser while it's running, that is asking for trouble. And if anyone else on your network uses this/browses EX at the same time you will definitely get banned. EX has also in the past changed how the banning system worked, so even if it's save now it might not be in six months. Also, if you have been banned in the recentish past, you have a lower tolerance for being banned again. Make sure you don't run this within a week or so of being banned.
Overall it should be save to use, but use some caution. Also, it's really slow, so be ready for that. Run it overnight or something.

Sorting by title works by trying to guess the "true name" of a gallery. Basically it removed anything in brackets, braces. or parens. So if the title from EX or the filename was "(C81) [English] My doujinshi", the name that we would use to sort is "My doujinshi". I felt this was more natural, especially when you might have something like this:
"(C81) [English] My doujinshi"
"My doujinshi - Part 2"

If we sorted by the raw title, those two would not be anywhere near each other in the list. 

Thanks for that. There should be some major enhancements coming soon. Next week there should be a new version with major performance increases (only really visible with 5k+ galleries) and before the end of the month there will be a completely new UI that doesn't look like a Windows 95 rip off.

**Comment by Triskov** [comment]
Apologies for the relative incoherence as I wrote that shortly before sleeping while deprived of such. 

**I'm assuming you mean a list view**
That's what I meant. I typed grid view because I was discussing on /a/ with Pewpews (who I saw was commenting on the other issue) on how I thought there should be a list view with columns, which they promptly added to theirs,  and they called it grid view so that's what came to mind first. The showing tags on mouse over is certainly nice as are the other mouse over features. Many of my concerns weren't particular relevant in yours though.  

**Custom tagging is already supported**
Good to know, I hadn't looked at it much yet.

**Anything you add will not overwrite data you might have from EX.**
I actually meant the other way around, but I can test it out and I assume it's the same.

**The one other user that uses this has also used it successfully.**
Hopefully it isn't that way for long. Certainly shouldn't be the case as far as I'm concerned.

**You should be able to use the auto search..Run it overnight or something.**
I'll try it out tonight and see how it goes. 

**Sorting by title works by trying to guess the "true name" of a gallery.**
I've provided a picture this time. Those with nudity have the thumbnails removed.
This is how the sorting starts out. Even with removing everything in parentheses for sorting, I don't understand how these are the first results, or the ordering at all still, despite your explanation. 
Though, before I saw your program I was of the mind that having each constituent part of the name parsed as a separate column was the ideal method. Whereas something like (Convention) [Circle (Artist)] Title (Franchise) [Language] [Translator] would be taken to its logical conclusion of having a different column for each, though in most use cases I think it would be Franchise - [Circle] Title for doujinshi and [artist] Title for manga. After trying yours out though, I think the way yours does it from what I can tell is more reliable and encompassing of varied naming structures. What could generally be found by sorting/filtering using columns can be done mostly through searching. 
![Pandaview](http://i.imgur.com/np6VQRp.png)

**I'm not sure what you mean by list by tag percentage. Something like "10% of galleries have tag 'X'"?**
I tagged three in Manga-Organizer to give an example. The problem in this case it does it out of everything rather than what is tagged. Though, since it includes tags such as translated, franchise, artist/circle, language, and others without segregation it may be of reduced effectiveness. When I saw it, I thought it might have interesting results that show "Oh, I guess I like [tag name] more/less than I thought I did " or "There sure are a lot of results that include [tag name], I hadn't noticed that. Maybe it's something I look for without realizing it?" to "I say that I don't like [tag name], but 17% of the works I have include it, I guess I'm in denial." Though, perhaps that isn't a high enough percent, same for claiming to like it a lot. Simply thoughts for consideration anyway.

![Tags1](http://i.imgur.com/yvt3Ye6.png)
![Tags2](http://i.imgur.com/m96DmUg.png)

**completely new UI that doesn't look like a Windows 95 rip off.**
I don't mind how it currently looks, but if you think it'll improve the aesthetics and functionality, I'm certainly interested to see how it goes. 

** There should be some major enhancements coming soon. Next week there should be a new version with major performance increases**
I will be putting out a basic organizational guide and reference post on /h/ soon. I doubt it'll have much impact, but since it'll be on the far slower /h/, it can be linked to in sadpanda threads for quite a while. The repository is called local sadpanda viewer,  the .exe is named SadPandaViewer and upon opening it, it is shown as Pandaviewer, so which do you want it to be specified as?

The guide will be in the format of a short review of the program, each with their own post and image. I have a basic/initial write-up complete, but it needs to be revised. When the UI and other major features are updated, a new image and information can be posted. I'll probably post it sometime in the next few days. It doesn't only cover the various programs for management. 

I would have replied sooner, but I really didn't expect you to reply so quickly, so I hadn't checked.

**Comment by Triskov** [comment]
I've ran the automated tagging without any problems. 
On this test, of the 10 pages, 3.5 pages were not able to obtain metadata. Probably from them being purged or otherwise not present. I haven't really checked yet. 
I'm undecided on how it changes the names as well, though only in the program. 
It would be appreciated if there was an easy way to see what doesn't have any tags after doing so.
Currently, the workaround for this is to not enter a custom rating for any gallery and then put sort by ascending rating, which will show everything untagged at the beginning. This precludes personal usage of the rating system, but I don't know if that's particularly a problem for users.  
I haven't done a thorough look through yet, but I've noticed a few where it chose a completely unrelated gallery.
One in particular that is confusing is the following. The first name is what I have the folder named as. The second is what it is named on exhentai.The third is what it thought it to be the correct gallery.
[Denki Shougun] Sleepover
[Denki Shougun] Sleepover part 1+2 (English) [desudesu]

[Urasekai 2] Super Hentai CG Shuu 12 Buta ni Kawarewru Mesu Dorei Sono 2 (Various) [English] [desudesu] [Incomplete]
 
It found almost all of the doujinshi, except a few. Here's an example that it was not able to find. First name is what I have it named. The second, third, and fourth names are what exhentai has it named.
KanColle - [Nekokaburi] Hisho Kan no O.YA.KU.ME
(C85) [Nekokaburi (Kuro no Miki)] Hisho Kan no O.YA.KU.ME (Kantai Collection -KanColle-) [English] [CGrascal]
(C85) [Nekokaburi (Kuro no Miki)] Hisho Kan no O.YA.KU.ME | Secretary Ship's D-U-T-Y (Kantai Collection) [English] {doujin-moe.us}
(C85) [Nekokaburi (Kuro no Miki)] Hisho Kan no O・YA・KU・ME (Kantai Collection)

I'm surprised by how well it works overall though.

**Comment by seanegoodwin** [comment]
There's a hilarious bug with the name sort. I accidentally introduced it at
few pushes ago. It'll be fixed in the next version.
I see what you mean with the tag percent thing. Interesting and could be
useful, but I wouldn't expect it anytime soon.
The UI change is mostly about switching to a framework that is easier to
develop for. The aesthetics are a nice benefit. I'm not removing any
functionality

As for the guide, I'm probably going to start using the name "PandaViewer".
But that's more for a lack of creativity and not because I like the name.
I'll probably start switching the stuff over sometime soon.


As for the false positives, I'll take a look at them. I don't get too much
data regarding this so anything is valuable. The searching code is the
oldest part of the program and probably could use some tweaks.
In the meantime, you can edit a gallery's ex link in the edit menu and it
will be fixed. Not a great solution for a lot of stuff, but it's there.

Finding all galleries without EX data is a good idea. I'll add it to my
backlog. Maybe another flag in the search bar: "no_ex_data=True" or
something.

The reason that gallery couldn't be found is that we strip out some special
characters from the name, including periods. I'm not entirely sure why that
is, and I didn't comment it. I'll see if anything breaks if stop doing
that.

If you find more false positives/galleries that can't be found, let me
know. That data is really useful. If send me the log file for this run, it
might help.

**Comment by Triskov** [comment]
Logs sent to didyouexpectarealemail@gmail.com

Link to initial version of guide. 
http://boards.4chan.org/h/thread/3975078/here-are-a-list-of-programs-scripts-and-various

I'll look for more of the mismatches and false negatives and comment if I see any.

**Comment by seanegoodwin** [comment]
Closing this for now. Some of the suggestions might end up getting implemented, but they are lower priority.
