### ISSUE TITLE
[Bug?] Saw this in the log

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#54]
Msg: file:///Q:/zPrograms/PandaViewer/qml/Material/Popover.qml:101: TypeError: Type error
2015-09-03 21:18:53,352: Logger.Qt logger INFO Kind: 1
Context: < PyQt5.QtCore.QMessageLogContext object at 0x0C954E30 >

It says it's an error, but I don't see any causing any problems. 
Maybe I'm just not noticing whatever it is supposed to not be doing. 
It seems to generate this every time the user does a mouseover of a gallery. 
I was going to mention this in the previous one I opened, but you closed it right away after I said nothing obviously doesn't work, so I waited until the new build was up to see if it still occurred.
Had to put spaces between the < > so it would appear.

**Comment by seanegoodwin** [comment]
Not really a bug/it doesn't cause problems so I haven't bothered to fix it. This has been around for a while - you are only seeing it now because I set things up to log UI errors instead of just suppressing them. There's a bunch of similar things you might see. Unless there are problems that you are seeing any messages like that can be ignored.
