### ISSUE TITLE
[PandaViewer] Version 0.9.1 -  It doesn't open. 

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#60]
![error](https://cloud.githubusercontent.com/assets/12780404/10413437/24ef8ff6-6f6e-11e5-8ba2-814ed8e02b06.jpg)

**Comment by seanegoodwin** [comment]
Can you try running it as admin? I'm seeing similar issues reported for other programs.

I really need to get a clean windows vm for testing.

**Comment by Triskov** [comment]
I tried. The exact same error appears.

**Comment by seanegoodwin** [comment]
Anyone else having the problem?

**Comment by Triskov** [comment]
Even if you aren't having this problem, it would be helpful to confirm that you aren't having it.

**Comment by seanegoodwin** [comment]
Can you try again? I've uploaded a new version.

**Comment by Triskov** [comment]
Sorry, I still get the same error.
Hopefully someone else comments.
I posted about in the thread as well in hopes that someone would comment.

**Comment by LoLsAlEd** [comment]
I am also having problems with the latest version, I keep getting this error and google is no help.
![error](https://cloud.githubusercontent.com/assets/13088744/10415295/624eabac-7036-11e5-9354-9a69bbf0f369.png)
I tried running the program in safemode and it didnt work, but when I tested it on a separate computer It worked, so the only thing I can think of that is causing this problem is a clash with another program. The only program that I can think of that could be affecting it is my install of python 3.5 but I just uninstalled it and it didn't work. So I'm kinda hoping you have some ideas as whats causing it.

**Comment by Black-Light** [comment]
Same issue here

**Comment by seanegoodwin** [comment]
What OS are you guys running. @LoLsAlEd What was the computer that worked running?

It works on both of my Windows machines, so I'm just trying to find a way to repo it.

**Comment by seanegoodwin** [comment]
Also - how did you guys install PV? Did you just copy over the old directory with the new one?

**Comment by Triskov** [comment]
I'm on Win 7 64 Bit. I downloaded the file and extracted it. I haven't ever copied over the old directory.

**Comment by LoLsAlEd** [comment]
On both PC's I'm running windows 10 x64bit, and to install I extacted it and copied in the exdb.sqlite.

**Comment by Black-Light** [comment]
Win 7 x64 here as well.

**Comment by Meowmel** [comment]
*cough cough*
The same as Black-Light.
![unbenannt3](https://cloud.githubusercontent.com/assets/10694804/10434045/4e1ea77c-7117-11e5-9624-4e7e64b1995c.JPG)

**Comment by seanegoodwin** [comment]
Just an update - I've managed to get a VM to reproduce the issue. 
The problem is that the new way of distributing the program doesn't seem to agree with some of the libraries I'm using. The reason I wanted to migrate to this new way is that it fixes https://github.com/seanegoodwin/PandaViewer/issues/59. 

I'm looking into solutions, but as this release doesn't contain too many changes (and nothing very important), I'm not in much of a hurry.

**Comment by Black-Light** [comment]
Any updates? I really want to use the new version with the ability to add meta-data from chaika.

**Comment by seanegoodwin** [comment]
Can someone who had this issue try the newest release? It worked on the two computers I tried it on so I'm hopeful.

**Comment by Meowmel** [comment]
Works here now

**Comment by Triskov** [comment]
Works here as well.

**Comment by seanegoodwin** [comment]
Excellent. Hopefully that is the end of these issues.
